import * as campaignModels from 'app/shared/models/campaign.model';

export interface CampaignDetailState {
  fetching: boolean;
  didFetch: boolean;
  campaign_id: string;
  is_old: boolean;
  data: campaignModels.CampaignDetail;
}

export const initialState: CampaignDetailState = {
  didFetch: false,
  fetching: false,
  campaign_id: '',
  is_old: false,
  data: {
    name: '',
    createdAt: '',
    createdBy: '',
    lastUpdateBy: '',
    lastUpdateAt: '',
    userId: '',
    messageTemplateGroupId: '',
    messageTemplateGroup: {
      groupId: '',
      name: '',
      createdBy: '',
      createdAt: '',
      lastUpdateBy: '',
      lastUpdateAt: '',
      isRemoved: false,
    },
    didPoolId: '',
    didPool: {
      messageGatewayProviderName: '',
      id: '',
      messageGatewayProviderId: '',
      createdAt: '',
      createdBy: '',
      maxDidPoolSize: 0,
      minPoolSize: 0,
      autoPurchaseDids: false,
      didCostAmount: 0,
      didCodeCostCurrency: '',
      lastUpdateBy: '',
      lastUpdateAt: '',
      username: '',
      password: '',
      name: '',
      currentSize: 0,
      mtSmsCost: null,
    },
    callImpressionUrl: '',
    destinationUrl: '',
    fileUrl: '',
    cronExpression: '',
    scheduleTime: '',
    disableCarrierCheck: false,
    injectTestMessageEvery: 0,
    deliveryInterval: '',
    routingPlanId: '',
    maxNumberOfSendMessagesForNoneClickers: 0,
    subDomainLength: 0,
    processingStatus: 0,
    validationCompletedAt: '',
    validationStartedAt: '',
    validationFailureReason: '',
    lastProcessingStartRequestedAt: '',
    lastProcessingStartedAt: '',
    lastProcessingStartRequestedBy: '',
    lastProcessingStartedBy: '',
    lastProcessingStartedFromSequenceNumber: 0,
    lastProcessingRunAt: '',
    lastProcessingException: '',
    lastProcessingStopRequestedBy: '',
    lastProcessingStopRequestedAt: '',
    lastProcessingStopException: '',
    lastProcessingStoppedAt: '',
    lastProcessingStoppedBy: '',
    lastMessageCraftingStartedAt: '',
    lastMessageCraftingFinishedAt: '',
    autoStart: false,
    initialProcessingBatchSize: 0,
    isEmpty: false,
    campaignSequenceNumber: 0,
    composerJobId: '',
    validationJobId: '',
    requestedProcessingBatchSize: 0,
    totalCampaignFileMessageCount: 0,
    totalSeedMessagesGenerated: 0,
    totalMessageCount: 0,
    totalBatchesAttemptedCount: 0,
    totalBatchesSuccessfullyCompletedCount: 0,
    badRecordsFoundCount: 0,
    vertical: '',
    fileTags: null,
    qualityCheckConcurrencyLimit: null,
    campaignRunnerConcurrencyLimit: null,
    conversationId: null,
  },
};
